version: 2

jobs:
  exec:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: 'Bundle install'
          command: 'bundle install'
      - run:
          name: "main"
          command: notify-yudachi


workflows:
  version: 2
  cron:
    jobs:
      - exec
    triggers:
      - schedule:
          cron: "0,3,10,20,30,40,50 * * * *"
          filters:
            branches:
              only:
                - master
